version: "2"
services:
  spark-master:
    image: ${PROJ}/multidev:${DEV_VERSION}
    container_name: spark-master
    mem_limit: 2g
    extends:
      service: sparkbase
      file: base.spark.yaml
    volumes:
      - ./data/spark/master/data:/data/master
      - ./data/spark/master/logs:/opt/spark/logs
      - ./data/spark/jars:/opt/spark/extra_jars
      - ./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    ports:
      - "${SPARK_PORT}:7077"
      - "${SPARK_UI_PORT}:8080"
    environment:
      - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY}
      - PYSPARK_SUBMIT_ARGS="--master spark://spark-master:7077 pyspark-shell"
    command: [
        "/opt/spark/sbin/start-master.sh",
        "--host", "0.0.0.0",
        "--port", "7077" ]
  spark-worker-1:
    image: ${PROJ}/multidev:${DEV_VERSION}
    container_name: spark-worker-1
    hostname: spark-worker-${DEV_VERISON}-1
    extends:
      service: sparkbase
      file: base.spark.yaml
    mem_limit: 2g
    volumes:
      - ./data/spark/worker/logs:/opt/spark/logs
      - ./data/spark/jars:/opt/spark/extra_jars
      - ./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_MASTER_HOST=spark-maser
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY}
    #      - PYSPARK_SUBMIT_ARGS="--master spark://spark-master:7077 pyspark-shell"
    command: [
        "/opt/spark/sbin/start-slave.sh",
        "spark://spark-master:7077"]
  spark-worker-2:
    extends:
      service: spark-worker-1
    container_name: spark-worker-2
    hostname: spark-worker-${DEV_VERISON}-2
  spark-worker-3:
    extends:
      service: spark-worker-1
    container_name: spark-worker-3
    hostname: spark-worker-${DEV_VERISON}-3
  spark-worker-4:
    extends:
      service: spark-worker-1
    container_name: spark-worker-4
    hostname: spark-worker-${DEV_VERISON}-4
  # spark-worker-5:
  #   extends:
  #     service: spark-worker-1
  #   container_name: spark-worker-5
  #   hostname: spark-worker-${DEV_VERISON}-5
  # spark-worker-6:
  #   extends:
  #     service: spark-worker-1
  #   container_name: spark-worker-6
  #   hostname: spark-worker-${DEV_VERISON}-6
  # spark-worker-7:
  #   extends:
  #     service: spark-worker-1
  #   container_name: spark-worker-7
  #   hostname: spark-worker-${DEV_VERISON}-7
  # spark-worker-8:
  #   extends:
  #     service: spark-worker-1
  #   container_name: spark-worker-8
  #   hostname: spark-worker-${DEV_VERISON}-8
networks:
  default:
    external:
      name: ${DOCKER_NETWORK}
