version: "2"
services:
  webdev-base:
    image: webdev:latest
    build:
      context: .
      args:
        - node_version=latest
        - ng_cli_version=latest
      dockerfile: web.Dockerfile
    volumes:
      - ~/data:/data
      - ./repos:/repos
  devserver:
    container_name: webdev-devserver
    extends: 
      service: webdev-base
    ports:
      - "42001:4200"
    working_dir: "/repos/${ACTIVE_REPO}"
    command: ["ng", "serve", "--host", "0.0.0.0"]
  webdev:
    container_name: webdev
    extends: 
      service: webdev-base
    ports:
      - "42000:4200"
    working_dir: "/repos/${ACTIVE_REPO}"
    #command: ["ng", "serve", "--host", "0.0.0.0"]
    command: /bin/bash -c "npm install && ng build --watch"
    labels:
      - "traefik.enable=false"
  nginx:
    container_name: nginx-dev
    image: nginx
    labels:
#      - "traefik.frontend.priority=1"
#      - "traefik.frontend.rule=Host:${TRAEFIK_DOMAIN}"
#      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    volumes:
      - ~/data:/data
      - ./repos:/repos
    environment:
      - SERVER_NAME=${TRAEFIK_DOMAIN}
      - STATIC_ROOT=${NGINX_STATIC_ROOT}
      - CONF_TEMPLATE=${NGINX_SERVICE_TEMPLATE}
    ports:
      - "${NGINX_PORT}:80"
    command: /bin/bash -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < $${CONF_TEMPLATE} > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    #command: ["/bin/bash", "-c", "envsubst < $${CONF_TEMPLATE} > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
    
networks:
  default:
    external:
      name: ${DOCKER_NETWORK}
